from dataclasses import replace

from .models import TaskSpec


def _task(task_id, title, difficulty, backend, category, source, description,
          input_spec, output_spec, constraints, evidence_rules, dimensions,
          tests, source_paths=None, status="catalogued"):
    return TaskSpec(task_id, title, difficulty, backend, description, input_spec,
                    output_spec, constraints, evidence_rules, category, source,
                    source_paths or [], dimensions, tests, status)


TASKS = {
    "silu_mul": _task("silu_mul", "Fused SiLU and multiply", "easy", "cuda", "elementwise", "sglang", "Compute silu(x[:D]) * x[D:] with one fused output kernel.", {"x": "[tokens, 2D] fp16/bf16"}, {"y": "[tokens, D] same dtype"}, ["support odd D", "no out-of-bounds tail access"], {"masked_load": ["S1"], "masked_store": ["S1"]}, {"memory": 2, "boundary": 2, "fusion": 1}, {"public": ["aligned D", "fp16"], "hidden": ["odd D", "bf16", "zero/large values"], "metamorphic": ["x=0 gives zero"]}, ["python/sglang/kernels/aot/tests/test_activation.py"], "mvp"),
    "rmsnorm": _task("rmsnorm", "RMSNorm kernel", "easy", "cuda", "norm_reduction", "sglang", "Normalize each row with FP32 accumulation and a learned weight.", {"x": "[tokens, hidden] fp16/bf16", "weight": "[hidden] fp16/bf16"}, {"y": "same shape and dtype as x"}, ["support non-aligned hidden sizes", "absolute error <= dtype tolerance"], {"fp32_accumulator": ["S2"], "masked_load": ["S1"], "warp_reduction": ["S2"]}, {"memory": 1, "boundary": 2, "reduction": 2, "numerical": 2}, {"public": ["hidden=1024", "fp16"], "hidden": ["hidden=111", "bf16", "production shapes"], "metamorphic": ["scale input and weight consistently"]}, ["python/sglang/kernels/aot/tests/test_norm.py"], "oracle_ready"),
    "fused_add_rmsnorm": _task("fused_add_rmsnorm", "Fused residual add and RMSNorm", "medium", "cuda", "fusion", "sglang", "Add residual in-place and normalize the result in one kernel.", {"x": "[tokens, hidden]", "residual": "same shape", "weight": "[hidden]"}, {"x": "normalized output", "residual": "updated residual"}, ["preserve residual semantics", "support fp16/bf16/fp32"], {"fp32_accumulator": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"fusion": 2, "boundary": 2, "reduction": 2, "numerical": 2}, {"public": ["aligned residual"], "hidden": ["non-aligned", "aliasing", "fp32"], "metamorphic": ["zero residual equals RMSNorm"]}, ["python/sglang/kernels/aot/tests/test_norm.py"]),
    "merge_state": _task("merge_state", "Attention state merge", "medium", "triton", "attention", "sglang/flashinfer", "Merge two attention partial states using numerically stable log-sum-exp.", {"states": "prefix/suffix output and LSE tensors"}, {"output": "merged state and LSE"}, ["handle positive infinity LSE", "support non-power-of-two head sizes"], {"fp32_accumulator": ["S2"], "masked_load": ["S1"]}, {"numerical": 2, "boundary": 2, "layout": 1, "fusion": 1}, {"public": ["finite LSE", "head_size=64"], "hidden": ["Inf LSE", "head_size=48", "613 tokens"], "metamorphic": ["swap prefix and suffix"]}, ["python/sglang/kernels/aot/tests/test_merge_state_v2.py"], "oracle_ready"),
    "moe_topk_softmax": _task("moe_topk_softmax", "MoE top-k softmax", "medium", "cuda", "moe_routing", "sglang", "Compute routing probabilities and top-k expert indices with optional renormalization.", {"gating": "[tokens, experts] fp16/bf16/fp32", "topk": "integer"}, {"weights": "[tokens, topk] fp32", "indices": "[tokens, topk] int32"}, ["support non-power-of-two expert counts", "define tie behavior"], {"fp32_accumulator": ["S1"], "warp_reduction": ["S1"], "masked_load": ["S1"]}, {"reduction": 2, "numerical": 2, "boundary": 1, "layout": 1}, {"public": ["experts=64", "topk=2"], "hidden": ["experts=12", "topk=10", "ties", "bf16"], "metamorphic": ["adding constant to logits preserves weights"]}, ["python/sglang/kernels/aot/tests/test_moe_topk_softmax.py"], "mvp"),
    "sampling": _task("sampling", "Top-k/top-p/min-p sampling", "medium", "cuda", "sampling", "flashinfer", "Sample token IDs after configurable top-k, top-p or min-p filtering.", {"logits": "[batch, vocab] fp32", "parameters": "per-batch k/p"}, {"token": "[batch] int32"}, ["define filter order", "respect legal candidate set", "seeded reproducibility"], {"masked_load": ["S1"], "fp32_accumulator": ["S2"]}, {"reduction": 1, "numerical": 2, "boundary": 2, "layout": 1}, {"public": ["top-k only", "top-p only"], "hidden": ["vocab=111", "p near 0/1", "joint filtering"], "metamorphic": ["sample belongs to retained set"]}, ["python/sglang/kernels/aot/tests/test_sampling.py"], "oracle_ready"),
    "tiled_gemm_bias": _task("tiled_gemm_bias", "Tiled GEMM with bias and activation", "medium", "tilelang", "gemm_fusion", "tilelang", "Compute C = activation(A @ B + bias) for fp16 matrices.", {"A": "[M,K] fp16", "B": "[K,N] fp16", "bias": "[N] fp32"}, {"C": "[M,N] fp16"}, ["support non-multiple M/N/K", "accumulate in fp32", "single fused epilogue"], {"tensor_core": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"memory": 2, "boundary": 2, "fusion": 2, "reduction": 2}, {"public": ["128x128x128"], "hidden": ["M/N/K non-aligned", "bias broadcast"], "metamorphic": ["bias=0 matches GEMM"]}),
    "online_softmax": _task("online_softmax", "Online softmax", "medium", "tilelang", "softmax_reduction", "tilelang", "Compute row-wise softmax without materializing an intermediate score matrix.", {"x": "[rows, cols] fp16/bf16"}, {"y": "same shape, row sums equal one"}, ["stable for large logits", "support non-power-of-two cols"], {"fp32_accumulator": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"reduction": 2, "numerical": 2, "boundary": 2, "memory": 1}, {"public": ["cols=128"], "hidden": ["cols=1537", "large logits", "all masked row"], "metamorphic": ["adding row constant preserves output"]}, status="oracle_ready"),
    "flashattention_small": _task("flashattention_small", "Reduced FlashAttention forward", "hard", "tilelang", "attention", "tilelang/flashinfer", "Compute causal scaled dot-product attention for bounded sequence and head dimensions.", {"qkv": "[batch, seq, heads, dim] fp16/bf16"}, {"output": "[batch, seq, heads, dim]"}, ["causal mask", "online softmax", "no full attention matrix"], {"tensor_core": ["S2"], "shared_memory": ["S1"], "masked_load": ["S3"]}, {"reduction": 2, "numerical": 2, "layout": 2, "boundary": 2, "fusion": 2}, {"public": ["seq=64", "dim=64"], "hidden": ["seq=127", "dim=48", "causal boundary"], "metamorphic": ["future tokens cannot affect output"]}),
    "paged_kv_gather": _task("paged_kv_gather", "Paged KV cache gather", "hard", "cuda", "kv_cache", "flashinfer", "Gather logical KV positions from a paged cache using a page table and slot mapping.", {"cache": "paged K/V tensors", "page_table": "int32", "positions": "int32"}, {"output": "logical K/V sequence"}, ["support fragmented pages", "handle final partial page", "no invalid slot access"], {"masked_load": ["S1"], "shared_memory": ["S2"]}, {"layout": 2, "boundary": 2, "memory": 2, "synchronization": 1}, {"public": ["contiguous pages"], "hidden": ["fragmented pages", "partial page", "empty sequence"], "metamorphic": ["identity page table equals contiguous gather"]}),
    "per_token_group_quant": _task("per_token_group_quant", "Per-token group FP8 quantization", "medium", "cuda", "quantization", "sglang/flashinfer", "Quantize each token by groups and return quantized values plus scales.", {"x": "[tokens, hidden] bf16/fp16", "group_size": "integer"}, {"y": "quantized tensor and scales"}, ["support hidden not divisible by group size", "scale uses FP32 max absolute value"], {"fp32_accumulator": ["S1"], "masked_load": ["S1"], "vectorized_load": ["S2"]}, {"numerical": 2, "boundary": 2, "memory": 2, "fusion": 1}, {"public": ["group=128"], "hidden": ["group=64/128", "non-aligned hidden", "zero group"], "metamorphic": ["dequantized error bounded by scale"]}, ["python/sglang/kernels/aot/tests/test_per_token_group_quant_8bit.py"]),
    "moe_align": _task("moe_align", "MoE token alignment", "hard", "cuda", "moe_routing", "sglang", "Sort and pad token-expert assignments into block-aligned expert segments.", {"topk_ids": "[tokens, topk] int32", "num_experts": "integer"}, {"output": "sorted ids, expert ids, padded count"}, ["preserve token multiplicity", "block alignment exact", "handle empty experts"], {"atomic": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"layout": 2, "boundary": 2, "synchronization": 2, "memory": 1}, {"public": ["balanced routing"], "hidden": ["empty expert", "all tokens same expert", "topk>1"], "metamorphic": ["permutation preserves counts"]}, ["python/sglang/kernels/aot/tests/test_moe_align.py"]),
    "hpc_rope_norm_store_kv": _task("hpc_rope_norm_store_kv", "RoPE + RMSNorm + paged KV write", "hard", "cuda", "fused_attention", "hpc-ops", "Apply optional Q/K normalization and RoPE, then write K/V rows into a paged cache.", {"qkv": "packed variable-length BF16", "kv_cache": "paged K/V", "page_table": "int32"}, {"q": "normalized/rotated Q", "kv_cache": "updated K/V"}, ["support prefill and decode metadata", "clear unused tail slots", "preserve qk norm policy"], {"masked_load": ["S1"], "shared_memory": ["S2"], "fp32_accumulator": ["S2"]}, {"layout": 2, "boundary": 2, "fusion": 2, "numerical": 2, "synchronization": 1}, {"public": ["prefill", "no norm"], "hidden": ["decode", "fragmented pages", "tail clear", "norm policy"], "metamorphic": ["identity RoPE preserves normalized values"]}, ["tests/test_rope.py"], "catalogued"),
    "hpc_rmsnorm_scale": _task("hpc_rmsnorm_scale", "Fused RMSNorm with FP8 scale", "medium", "cuda", "quantization", "hpc-ops", "Return FP32-normalized output and scaled FP8 output from one normalization pass.", {"x": "[tokens, hidden] bf16", "weight": "[hidden] bf16", "scale": "fp32"}, {"output": "fp32 and fp8/bf16 tensors"}, ["FP32 norm accumulation", "quantization error within tolerance", "optional MoE scale"], {"fp32_accumulator": ["S1"], "vectorized_load": ["S2"], "masked_load": ["S1"]}, {"numerical": 2, "boundary": 1, "fusion": 2, "memory": 2}, {"public": ["scale=2.5"], "hidden": ["scale extremes", "Moe scale vector", "non-aligned hidden"], "metamorphic": ["scale changes only quantized branch"]}, ["tests/test_normalization.py"], "oracle_ready"),
    "hpc_route_gemm": _task("hpc_route_gemm", "BF16 x FP32 route GEMM", "hard", "cuda", "gemm_precision", "hpc-ops", "Compute a precision-sensitive GEMM using high/low BF16 decomposition of FP32 weights.", {"A": "[M,K] bf16", "B": "[K,N] fp32-decomposed", "scale": "1/256"}, {"C": "[M,N] fp32"}, ["preserve FP32-sensitive accuracy", "fused high/low GEMM", "support non-aligned dimensions"], {"tensor_core": ["S2"], "shared_memory": ["S1"], "fp32_accumulator": ["S2"]}, {"reduction": 2, "numerical": 2, "fusion": 2, "boundary": 2, "memory": 2}, {"public": ["aligned GEMM"], "hidden": ["M/N/K non-aligned", "small residual", "large K"], "metamorphic": ["zero residual reduces to high component GEMM"]}, ["tests/test_gemm_bf16xfp32.py"], "oracle_ready"),
    "hpc_group_gemm_fp8": _task("hpc_group_gemm_fp8", "Grouped FP8 GEMM", "hard", "cuda", "grouped_gemm", "hpc-ops", "Run independent GEMMs for routed groups with per-group FP8 scaling.", {"A": "grouped activations", "B": "grouped FP8 weights", "group_sizes": "int32"}, {"C": "grouped outputs"}, ["preserve group boundaries", "support empty groups", "per-group scales"], {"tensor_core": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"layout": 2, "boundary": 2, "fusion": 2, "memory": 2, "synchronization": 1}, {"public": ["balanced groups"], "hidden": ["empty group", "skewed groups", "non-aligned N"], "metamorphic": ["permuting groups permutes outputs"]}, ["tests/test_group_gemm_blockwise.py", "tests/test_group_gemm_pertensor.py"], "catalogued"),
    "hpc_attention_decode": _task("hpc_attention_decode", "Paged decode attention", "hard", "cuda", "attention", "hpc-ops", "Compute decode attention over a paged KV cache with variable request lengths.", {"q": "[batch, heads, dim]", "kv_cache": "paged K/V", "lengths": "int32"}, {"output": "[batch, heads, dim]"}, ["variable lengths", "paged cache", "causal decode semantics"], {"tensor_core": ["S2"], "masked_load": ["S1"], "shared_memory": ["S2"]}, {"layout": 2, "boundary": 2, "numerical": 2, "memory": 2, "synchronization": 2}, {"public": ["uniform lengths"], "hidden": ["mixed lengths", "empty/short request", "fragmented pages"], "metamorphic": ["increasing cache with zero suffix is stable"]}, ["tests/test_attention_decode_bf16.py"], "extension"),
}

_TESTS_READY = {
    "rmsnorm",
    "merge_state",
    "sampling",
    "online_softmax",
    "hpc_rmsnorm_scale",
    "hpc_route_gemm",
    "silu_mul",
    "fused_add_rmsnorm",
    "moe_topk_softmax",
    "tiled_gemm_bias",
    "per_token_group_quant",
    "flashattention_small",
    "paged_kv_gather",
    "moe_align",
    "hpc_rope_norm_store_kv",
    "hpc_group_gemm_fp8",
    "hpc_attention_decode",
}
TASKS = {
    task_id: replace(task, status="tests_ready") if task_id in _TESTS_READY else task
    for task_id, task in TASKS.items()
}
